version: '3.9'
services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
  web:
    build: .
    ports:
      - 80:8000
    depends_on:
      - db


volumes:
  postgres_data:
