# Generated by Django 3.2.13 on 2022-06-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnitHistory',
            fields=[
                ('id', models.IntegerField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('oldId', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=100)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.shopunithistory')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=100)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.shopunit')),
            ],
        ),
    ]
